@startuml Exchange Data Models

entity Users {
    * user_id : 64-bit Integer <<generated>>
    --
    * email : string
    * address : string

}

entity Wallet {
    * wallet_id : 64-bit Integer <<generated>>
    --
    * user_id : 64-bit Integer <<FK>>
}

entity Instrument {
    * instrument_id : 64-bit Integer <<generated>>
    --
    * instrument_name : string
    * instrument_ticket : char[4]
}

entity Asset_Balance {
    * asset_balance_id : 64-bit Integer <<generated>>
    --
    * instrument_id : 64-bit Integer <<FK>>
    * currency_id : 64-bit Integer <<FK>>
    * balance : float 
    * wallet_id : 64-bit Integer <<FK>>
}

entity Currency {
    * currency_id : 64-bit Integer <<generated>>
    --
    * name : string
    * currency_ticker : char[3]
}



entity Execution {

}

entity Trade {

}



Users ||--|{ Wallet
Asset_Balance }|--|| Wallet
Asset_Balance ||--|| Instrument
Asset_Balance ||--|| Currency

@enduml