@startuml Rewards Transmission Before Sequence Diagram
autonumber
actor Customer

Customer -> Amazon: Place Order
Amazon --> Customer: Success

Amazon -> Amazon: Shipment Started Event
Amazon -> Amex: Authorize Shipment Funds

alt Success
    Amex --> Amazon: Success

else Insufficient Funds or Other Error
    Amex --> Amazon: Failure
    Amazon -> Amazon: Cancel Order
end

Amazon -> Amazon: Shipment Complete Event
Amazon -> Amazon: Process Payment

Amazon -> PaymentTech: Send Settlement Batch File
PaymentTech -> PaymentTech: Validate Settlement Batch File
PaymentTech -> Amex: Send Amex Transactions


@enduml